// Feed router.
//
// `recordShift` mutation: writes one row to public.opinion_shifts. RLS policy
// `opinion_shifts_insert_self` (migration 0005) gates the user_id; the write
// goes through `ctx.db` (user-scoped) so the bearer token is the authority.
//
// Per-submit idempotency (#127 H11 PR B2): the client sends a per-tap uuid
// `clientKey`. It is stored on the inserted row. The partial unique index
// `opinion_shifts_user_client_key_uniq` on (user_id, client_key) added by
// migration 20260930000000 rejects a second write with the same pair,
// returning sqlstate `23505`. On that error the handler falls back to a
// self-scoped SELECT of the existing row (by user_id + client_key) and
// returns it as an ordinary success — a retry after a lost response looks
// the same to the caller as a first-time success. `NULL != NULL` in
// Postgres unique indexes so the partial predicate also lets multiple
// legitimate change-of-mind rows (different keys) coexist on the same
// (user_id, topic_id) — see docs/MASTER_PLAN.md:179.
//
// clientKey is OPTIONAL at the input layer during the rollout window:
// PWA users on stale cached bundles will keep sending requests without
// it. A missing key writes the row on the legacy path (no idempotency
// enforcement — same failure mode as before B2). A present-but-invalid
// key (non-UUID) is rejected at the schema layer. Once
// `opinion_shifts.client_key IS NOT NULL` for all recent rows in prod
// the field should be tightened to required — filed as a follow-up.
//
// `list` query: returns today's Drop (the news_topics row with is_drop=true
// whose drop_at has passed) or the most-recent past Drop if today's hasn't
// fired yet. Length ≤ 1 in default-input mode; forward-compatible with
// archive pagination via { limit, cursor }. RLS read-all is in place on
// news_topics via `news_topics_select_all` (migration 20260420090005:26).

import { TRPCError } from '@trpc/server';
import { z } from 'zod';

import { mutationLimit, queryLimit } from '../rate-limit.js';
import { protectedProcedure, router } from '../trpc.js';

const positionSchema = z.number().int().min(-2).max(2);

const listInputSchema = z
  .object({
    limit: z.number().int().min(1).max(50).default(1),
    // ISO timestamp; rows returned have drop_at <= cursor. Default is the
    // current server time so the no-input call returns "the current Drop".
    // Rejected if it lies in the future — a `cursor=9999-…` call would
    // otherwise return any pre-populated future-dated row the moment
    // drop_publish lands it, before its drop_at arrives. The pipeline
    // today stamps drop_at at INSERT time, but a future curator path
    // (the curation_mode enum already accommodates it) is the kind of
    // writer this guard exists for. The handler also clamps server-side
    // (defense in depth against any future input-schema regression).
    cursor: z
      .string()
      .datetime()
      .optional()
      .refine((v) => v === undefined || Date.parse(v) <= Date.now(), {
        message: 'cursor must not be in the future',
      }),
  })
  .optional();

const TOPIC_SELECT =
  'id, headline, source_title, summary, primary_source_url, category, drop_at, dedup_cluster_id, curation_mode, is_block_exhausted, additional_sources';

interface TopicRow {
  id: string;
  headline: string;
  source_title: string | null;
  summary: string | null;
  primary_source_url: string | null;
  category: string | null;
  drop_at: string | null;
  dedup_cluster_id: string | null;
  curation_mode: string | null;
  is_block_exhausted: boolean;
  additional_sources: unknown;
}

export const feedRouter = router({
  recordShift: protectedProcedure
    // M5 — 10/min per user. One stance per Drop in practice; 10/min
    // is the anti-bot floor.
    //
    // The outer mutationLimit stays — it is the per-process ceiling that
    // throttles a flooding client at the tRPC boundary. The RPC's own
    // rolling-24h cap (migration 20261010000000, PR A of #145) is a
    // defence-in-depth atomic ceiling INSIDE the DB transaction, serialized
    // per-user via pg_advisory_xact_lock so parallel bursts cannot slip
    // through between the COUNT and the INSERT.
    .use(mutationLimit('feed.recordShift', { perMin: 10 }))
    .input(
      z.object({
        topicId: z.string().uuid(),
        afterPosition: positionSchema,
        // Per-tap idempotency key generated by the client. See file
        // header. Optional during the rollout window so stale-PWA
        // clients continue to succeed. A present-but-invalid value is
        // still rejected — `.uuid()` runs whenever the field is passed.
        clientKey: z.string().uuid().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      // #145 PR B: the write runs through `record_opinion_shift(uuid,
      // smallint, uuid)` — a SECURITY DEFINER RPC that derives user_id
      // from auth.uid(), snapshots before_position server-side (replacing
      // the H13 pre-select below), enforces a rolling-24h cap, and
      // ON CONFLICT no-ops the Take 5 after-insert trigger on retry. The
      // RPC returns the opinion_shifts row either freshly inserted or
      // pre-existing from an idempotent retry — identical wire shape to
      // the previous .insert() path.
      //
      // PR A of #145 (migration 20261010000000) landed the RPC; PR C
      // drops the client-side `opinion_shifts_insert_self` policy, at
      // which point this is the only writer and the RPC's cap + snapshot
      // guarantees cannot be bypassed via direct PostgREST.
      const { data, error } = await ctx.db.rpc('record_opinion_shift', {
        p_topic_id: input.topicId,
        p_after_position: input.afterPosition,
        p_client_key: input.clientKey ?? undefined,
      });

      if (error) {
        // Map RPC SQLSTATE → tRPC code. Each raise in the RPC uses a
        // specific code so the client (and the mutationLimit middleware)
        // can distinguish retryable from terminal. The `cause` carries
        // only the SQLSTATE so the raw PostgrestError's
        // message/details/hint (which can carry schema/constraint names
        // or raised-exception text) never reaches the tRPC wire
        // response — same wire-safety wrap as the pre-RPC path.
        const code = error.code;
        if (code === 'P0002') {
          // topic not found — client should clear the card from its
          // local queue without retrying.
          throw new TRPCError({ code: 'NOT_FOUND', message: 'Topic not found.' });
        }
        if (code === '54000') {
          // rolling-24h cap hit. TOO_MANY_REQUESTS classifies the
          // response for consistent client-side retry logic.
          throw new TRPCError({
            code: 'TOO_MANY_REQUESTS',
            message: 'Too many opinion shifts in the last 24 hours.',
            cause: new Error(code),
          });
        }
        if (code === '22023') {
          // after_position out of range — client bug. BAD_REQUEST so
          // the fetch is not retried.
          throw new TRPCError({
            code: 'BAD_REQUEST',
            message: 'Invalid stance.',
            cause: new Error(code),
          });
        }
        if (code === '28000') {
          // auth.uid() came back null inside the RPC. Should be
          // unreachable from protectedProcedure (which 401s before any
          // handler body), but defence-in-depth classification.
          throw new TRPCError({
            code: 'UNAUTHORIZED',
            message: 'Not authenticated.',
            cause: new Error(code),
          });
        }
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to record opinion shift.',
          cause: new Error(code ?? 'db_error'),
        });
      }

      if (!data) {
        // The RPC's return type is a composite row; a null result here
        // would mean supabase-js dropped the payload. Prefer
        // INTERNAL_SERVER_ERROR over silently fabricating a success.
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to record opinion shift.',
          cause: new Error('rpc_null_result'),
        });
      }

      return {
        id: data.id,
        topicId: data.topic_id,
        beforePosition: data.before_position,
        afterPosition: data.after_position,
        createdAt: data.created_at,
      };
    }),

  list: protectedProcedure
    // M5.1 — 60/min per user. Cold read (no client polling), single
    // call site (DropFeedClient on home). 1 DB query. Generous cap
    // for the home-page rapid-navigation case.
    .use(queryLimit('feed.list', { perMin: 60 }))
    .input(listInputSchema)
    .query(async ({ ctx, input }) => {
      // Belt-and-suspenders future-clamp: the input schema already
      // rejects future cursors, but a server-side Math.min closes the
      // window against any later input-schema regression.
      const requestedCursorMs = input?.cursor ? Date.parse(input.cursor) : Date.now();
      const cursor = new Date(Math.min(requestedCursorMs, Date.now())).toISOString();
      const limit = input?.limit ?? 1;

      const { data, error } = (await ctx.db
        .from('news_topics')
        .select(TOPIC_SELECT)
        .eq('is_drop', true)
        .lte('drop_at', cursor)
        .order('drop_at', { ascending: false })
        .limit(limit)) as unknown as {
        data: TopicRow[] | null;
        error: { message: string } | null;
      };

      if (error) {
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to load Drop.',
          cause: error,
        });
      }

      const topicRows = data ?? [];
      const topicIds = topicRows.map((row) => row.id);

      // Per-user latest-stance lookup for P2.a. One query across the
      // returned topics (uses the composite index on
      // (user_id, topic_id, created_at desc) added in migration
      // 20260420090011). Mapped to {agree, disagree, null}; a null
      // keeps the DropCard's buttons in their neutral unselected state.
      const latestStance: Record<string, 'agree' | 'disagree' | null> = {};
      if (topicIds.length > 0) {
        const { data: shiftRows, error: shiftErr } = (await ctx.db
          .from('opinion_shifts')
          .select('topic_id, after_position, created_at')
          .eq('user_id', ctx.userId)
          .in('topic_id', topicIds)
          .order('created_at', { ascending: false })) as unknown as {
          data: { topic_id: string; after_position: number; created_at: string }[] | null;
          error: { message: string } | null;
        };
        if (shiftErr) {
          // Non-fatal — a stance-lookup failure must not block the Drop
          // from rendering. Fall through with an empty map so the
          // DropCard shows neutral buttons.
          console.warn(
            JSON.stringify({
              event: 'feed.list.stance_lookup_failed',
              message: shiftErr.message,
            }),
          );
        } else {
          for (const row of shiftRows ?? []) {
            if (row.topic_id in latestStance) continue; // first row wins (ordered desc)
            latestStance[row.topic_id] =
              row.after_position > 0 ? 'agree' : row.after_position < 0 ? 'disagree' : null;
          }
        }
      }

      const topics = topicRows.map((row) => ({
        id: row.id,
        headline: row.headline,
        sourceTitle: row.source_title,
        summary: row.summary,
        primarySourceUrl: row.primary_source_url,
        category: row.category,
        dropAt: row.drop_at,
        dedupClusterId: row.dedup_cluster_id,
        curationMode: row.curation_mode,
        isBlockExhausted: row.is_block_exhausted,
        additionalSources: Array.isArray(row.additional_sources) ? row.additional_sources : [],
        userStance: latestStance[row.id] ?? null,
      }));

      return { topics };
    }),
});
