// Feed router.
//
// `recordShift` mutation: writes one row to public.opinion_shifts. RLS policy
// `opinion_shifts_insert_self` (migration 0005) gates the user_id; the write
// goes through `ctx.db` (user-scoped) so the bearer token is the authority.
//
// Per-submit idempotency (#127 H11 PR B2): the client sends a per-tap uuid
// `clientKey`. It is stored on the inserted row. The partial unique index
// `opinion_shifts_user_client_key_uniq` on (user_id, client_key) added by
// migration 20260930000000 rejects a second write with the same pair,
// returning sqlstate `23505`. On that error the handler falls back to a
// self-scoped SELECT of the existing row (by user_id + client_key) and
// returns it as an ordinary success — a retry after a lost response looks
// the same to the caller as a first-time success. `NULL != NULL` in
// Postgres unique indexes so the partial predicate also lets multiple
// legitimate change-of-mind rows (different keys) coexist on the same
// (user_id, topic_id) — see docs/MASTER_PLAN.md:179.
//
// clientKey is OPTIONAL at the input layer during the rollout window:
// PWA users on stale cached bundles will keep sending requests without
// it. A missing key writes the row on the legacy path (no idempotency
// enforcement — same failure mode as before B2). A present-but-invalid
// key (non-UUID) is rejected at the schema layer. Once
// `opinion_shifts.client_key IS NOT NULL` for all recent rows in prod
// the field should be tightened to required — filed as a follow-up.
//
// `list` query: returns today's Drop (the news_topics row with is_drop=true
// whose drop_at has passed) or the most-recent past Drop if today's hasn't
// fired yet. Length ≤ 1 in default-input mode; forward-compatible with
// archive pagination via { limit, cursor }. RLS read-all is in place on
// news_topics via `news_topics_select_all` (migration 20260420090005:26).

import { TRPCError } from '@trpc/server';
import { z } from 'zod';

import { mutationLimit, queryLimit } from '../rate-limit.js';
import { protectedProcedure, router } from '../trpc.js';

const positionSchema = z.number().int().min(-2).max(2);

const listInputSchema = z
  .object({
    limit: z.number().int().min(1).max(50).default(1),
    // ISO timestamp; rows returned have drop_at <= cursor. Default is the
    // current server time so the no-input call returns "the current Drop".
    // Rejected if it lies in the future — a `cursor=9999-…` call would
    // otherwise return any pre-populated future-dated row the moment
    // drop_publish lands it, before its drop_at arrives. The pipeline
    // today stamps drop_at at INSERT time, but a future curator path
    // (the curation_mode enum already accommodates it) is the kind of
    // writer this guard exists for. The handler also clamps server-side
    // (defense in depth against any future input-schema regression).
    cursor: z
      .string()
      .datetime()
      .optional()
      .refine((v) => v === undefined || Date.parse(v) <= Date.now(), {
        message: 'cursor must not be in the future',
      }),
  })
  .optional();

const TOPIC_SELECT =
  'id, headline, source_title, summary, primary_source_url, category, drop_at, dedup_cluster_id, curation_mode, is_block_exhausted, additional_sources';

interface TopicRow {
  id: string;
  headline: string;
  source_title: string | null;
  summary: string | null;
  primary_source_url: string | null;
  category: string | null;
  drop_at: string | null;
  dedup_cluster_id: string | null;
  curation_mode: string | null;
  is_block_exhausted: boolean;
  additional_sources: unknown;
}

export const feedRouter = router({
  recordShift: protectedProcedure
    // M5 — 10/min per user. One stance per Drop in practice; 10/min
    // is the anti-bot floor.
    .use(mutationLimit('feed.recordShift', { perMin: 10 }))
    .input(
      z.object({
        topicId: z.string().uuid(),
        beforePosition: positionSchema,
        afterPosition: positionSchema,
        // Per-tap idempotency key generated by the client. See file
        // header. Optional during the rollout window so stale-PWA
        // clients continue to succeed. A present-but-invalid value is
        // still rejected — `.uuid()` runs whenever the field is passed.
        clientKey: z.string().uuid().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      // Build the insert payload. When no clientKey is provided (stale
      // client) omit the column so it lands as NULL — the partial unique
      // index skips NULL rows, so the legacy write path stays exactly
      // as it was pre-B2 for those callers.
      const insertPayload: {
        user_id: string;
        topic_id: string;
        before_position: number;
        after_position: number;
        client_key?: string;
      } = {
        user_id: ctx.userId,
        topic_id: input.topicId,
        before_position: input.beforePosition,
        after_position: input.afterPosition,
      };
      if (input.clientKey !== undefined) {
        insertPayload.client_key = input.clientKey;
      }

      const { data, error } = await ctx.db
        .from('opinion_shifts')
        .insert(insertPayload)
        .select('id, topic_id, before_position, after_position, created_at')
        .maybeSingle();

      if (error) {
        // 23503 fk_violation — the topic id doesn't exist. Surface as
        // NOT_FOUND so the client can clear the card from the local
        // queue without retrying.
        if (error.code === '23503') {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Topic not found.',
          });
        }
        // 23505 unique_violation on (user_id, client_key): the client
        // already wrote this exact tap. Retry-after-lost-response case.
        // Reachable only when input.clientKey was provided (otherwise
        // client_key is NULL and the partial index doesn't apply).
        // Look up the existing row through the SAME user-scoped ctx.db
        // (RLS gates the SELECT to auth.uid()'s own rows), AND filter
        // explicitly on user_id + client_key so a hypothetical
        // cross-user uuid collision cannot leak another user's row via
        // the client-supplied key. `opinion_shifts_select_self` RLS is
        // the belt; the .eq('user_id', ...) is the suspenders.
        if (error.code === '23505' && input.clientKey !== undefined) {
          const { data: existing, error: lookupError } = await ctx.db
            .from('opinion_shifts')
            .select('id, topic_id, before_position, after_position, created_at')
            .eq('user_id', ctx.userId)
            .eq('client_key', input.clientKey)
            .maybeSingle();

          if (lookupError || !existing) {
            // Should be unreachable — 23505 means a matching row exists.
            // If we can't fetch it, prefer INTERNAL_SERVER_ERROR to a
            // silent success (never fabricate an insert result).
            throw new TRPCError({
              code: 'INTERNAL_SERVER_ERROR',
              message: 'Failed to reconcile duplicate opinion shift.',
              cause: lookupError ?? error,
            });
          }
          return {
            id: existing.id,
            topicId: existing.topic_id,
            beforePosition: existing.before_position,
            afterPosition: existing.after_position,
            createdAt: existing.created_at,
          };
        }
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to record opinion shift.',
          cause: error,
        });
      }
      if (!data) {
        throw new TRPCError({ code: 'NOT_FOUND', message: 'Topic not found.' });
      }
      return {
        id: data.id,
        topicId: data.topic_id,
        beforePosition: data.before_position,
        afterPosition: data.after_position,
        createdAt: data.created_at,
      };
    }),

  list: protectedProcedure
    // M5.1 — 60/min per user. Cold read (no client polling), single
    // call site (DropFeedClient on home). 1 DB query. Generous cap
    // for the home-page rapid-navigation case.
    .use(queryLimit('feed.list', { perMin: 60 }))
    .input(listInputSchema)
    .query(async ({ ctx, input }) => {
      // Belt-and-suspenders future-clamp: the input schema already
      // rejects future cursors, but a server-side Math.min closes the
      // window against any later input-schema regression.
      const requestedCursorMs = input?.cursor ? Date.parse(input.cursor) : Date.now();
      const cursor = new Date(Math.min(requestedCursorMs, Date.now())).toISOString();
      const limit = input?.limit ?? 1;

      const { data, error } = (await ctx.db
        .from('news_topics')
        .select(TOPIC_SELECT)
        .eq('is_drop', true)
        .lte('drop_at', cursor)
        .order('drop_at', { ascending: false })
        .limit(limit)) as unknown as {
        data: TopicRow[] | null;
        error: { message: string } | null;
      };

      if (error) {
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to load Drop.',
          cause: error,
        });
      }

      const topics = (data ?? []).map((row) => ({
        id: row.id,
        headline: row.headline,
        sourceTitle: row.source_title,
        summary: row.summary,
        primarySourceUrl: row.primary_source_url,
        category: row.category,
        dropAt: row.drop_at,
        dedupClusterId: row.dedup_cluster_id,
        curationMode: row.curation_mode,
        isBlockExhausted: row.is_block_exhausted,
        additionalSources: Array.isArray(row.additional_sources) ? row.additional_sources : [],
      }));

      return { topics };
    }),
});
